Update Readme.md - Cohort 5
r4ds/bookclub-Advanced_R pull request #258
Opened 2021-06-08 18:38 UTC by HannesOberreiter

Added slides for my presentation of Chapter 12 + 13.

2021-06-13 13:45 UTC, tanho63 requested changes
Hiya @HannesOberreiter ! Can you also add a copy of your RMD and HTML files to the appropriate folders? This makes it easier for someone to reproduce your slides later!

2021-06-13 17:07 UTC, HannesOberreiter commented
@tanho63 done.

PS: The whole week concept is a little bit confusing if you one does not keep track of it.

2021-06-17 06:02 UTC, HannesOberreiter commented
Added Chapter 14. I did spontaneous substitute and used the slides from a previous cohort.

2021-07-27 13:39 UTC, tanho63 approved these changes

2021-07-27 13:39 UTC, merged